### ISSUE TITLE
innerHTML vs innerText

### ISSUE THREAD

**Issue by thuyanduong-flatiron** [learn-co-curriculum/fewpjs-removing-altering-and-inserting-html-lab#4]
In the instructions, we introduce the students to .innerHTML and not .innerText yet. In the lab, I tried 
```
newHeader.innerHTML = 'Ann is the champion'
```
but I can only get the test case to pass if I do 

```
newHeader.innerText = 'Ann is the champion'
```

**Comment by drakeltheryuujin** [comment]
Hi @thuyanduong-flatiron,

Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
We apologize for any frustration you might have encountered during this process but thank you for reporting this so that it may be resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
